name: example
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.14.0
  jaspr_router: ^0.5.0
  jaspr_clean_syntax: any
  
dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.14.0
  lints: ^3.0.0

jaspr:
  mode: static

