name: jaspr_clean_syntax
description: Simplified Jasper Syntax
version: 0.1.0+2
homepage: https://www.flutterplaza.com/
repository: https://github.com/FlutterPlaza/jasprfire/tree/main/packages/jaspr_clean_syntax
publish_to: 'none'


environment:
  sdk: ^3.4.0

dependencies: 
  jaspr: ^0.14.0
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0

